using DiffPdf.Core.Models;
using DiffPdf.Pdf;

namespace DiffPdf.Core.Tests;

/// <summary>
/// Contract of <see cref="PdfPigTextExtractor.ProbeAndExtractAsync"/> — the single-open probe + extraction
/// the engine uses: status + geometry + pages from one pass, page-range filtering, and the defensive
/// statuses (unreadable / missing) with empty pages. Uses real PDFs generated by PdfSharp.
/// </summary>
public sealed class PdfPigTextExtractorTests : IDisposable
{
    private readonly string _dir = Directory.CreateTempSubdirectory("diffpdf-extractor-").FullName;

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); } catch { /* best-effort temp cleanup */ }
    }

    private string CreatePdf(int pageCount)
    {
        using var doc = new PdfSharp.Pdf.PdfDocument();
        for (int i = 0; i < pageCount; i++) doc.AddPage();
        string path = Path.Combine(_dir, $"doc-{pageCount}.pdf");
        doc.Save(path);
        return path;
    }

    [Fact]
    public async Task SingleOpen_ReturnsStatusGeometryAndPagesTogether()
    {
        var result = await new PdfPigTextExtractor().ProbeAndExtractAsync(CreatePdf(3), PageRange.All);

        Assert.Equal(DocumentStatus.Ok, result.Info.Status);
        Assert.Equal(3, result.Info.PageCount);
        Assert.Equal([1, 2, 3], result.Info.Pages.Select(g => g.PageNumber));
        Assert.Equal([1, 2, 3], result.Pages.Select(p => p.PageNumber));
    }

    [Fact]
    public async Task PageRange_FiltersExtractionButKeepsFullGeometry()
    {
        var result = await new PdfPigTextExtractor().ProbeAndExtractAsync(CreatePdf(3), new PageRange(2, 2));

        Assert.Equal(3, result.Info.PageCount);
        Assert.Equal(3, result.Info.Pages.Count);
        var page = Assert.Single(result.Pages);
        Assert.Equal(2, page.PageNumber);
    }

    [Fact]
    public async Task GarbageFile_ReportsUnreadableWithNoPages()
    {
        string path = Path.Combine(_dir, "garbage.pdf");
        await File.WriteAllBytesAsync(path, [1, 2, 3, 4]);

        var result = await new PdfPigTextExtractor().ProbeAndExtractAsync(path, PageRange.All);

        Assert.Equal(DocumentStatus.Unreadable, result.Info.Status);
        Assert.False(result.Info.IsComparable);
        Assert.Empty(result.Pages);
    }

    [Fact]
    public async Task MissingFile_ReportsNotFound()
    {
        var result = await new PdfPigTextExtractor()
            .ProbeAndExtractAsync(Path.Combine(_dir, "missing.pdf"), PageRange.All);

        Assert.Equal(DocumentStatus.NotFound, result.Info.Status);
        Assert.Empty(result.Pages);
    }

    [Fact]
    public async Task MatchesTheSplitProbeAndExtractPath()
    {
        // The combined call must agree with the legacy two-open path the default interface method uses.
        var extractor = new PdfPigTextExtractor();
        string path = CreatePdf(2);

        var combined = await extractor.ProbeAndExtractAsync(path, PageRange.All);
        var probed = extractor.Probe(path);
        var extracted = await extractor.ExtractAsync(path, PageRange.All);

        Assert.Equal(probed.Status, combined.Info.Status);
        Assert.Equal(probed.PageCount, combined.Info.PageCount);
        Assert.Equal(probed.Pages.Select(g => g.PageNumber), combined.Info.Pages.Select(g => g.PageNumber));
        Assert.Equal(extracted.Select(p => p.PageNumber), combined.Pages.Select(p => p.PageNumber));
    }
}
