<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DiffPdf.Application.Abstractions\DiffPdf.Application.Abstractions.csproj" />
    <ProjectReference Include="..\DiffPdf.Core\DiffPdf.Core.csproj" />
    <ProjectReference Include="..\DiffPdf.Persistence\DiffPdf.Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DiffPdf.Core.Tests" />
  </ItemGroup>

</Project>
