<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DiffPdf.Application.Abstractions\DiffPdf.Application.Abstractions.csproj" />
    <ProjectReference Include="..\DiffPdf.Core\DiffPdf.Core.csproj" />
    <ProjectReference Include="..\DiffPdf.Notifications\DiffPdf.Notifications.csproj" />
    <ProjectReference Include="..\DiffPdf.Persistence\DiffPdf.Persistence.csproj" />
    <ProjectReference Include="..\DiffPdf.Worker\DiffPdf.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" Version="0.13.0" />
    <PackageReference Include="WolverineFx" Version="6.29.2" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="6.29.2" />
    <PackageReference Include="WolverineFx.SqlServer" Version="6.29.2" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.29.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DiffPdf.Core.Tests" />
  </ItemGroup>

</Project>
